github: [metadata]
encoding: UTF-8
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  syntax_highlighter: rouge
future: true
jailed: false
gfm_quirks: paragraph_end
plugins:
  - jekyll-postcss
lsi: false
safe: true
incremental: false
gist:
  noscript: false
title: Thomas Hareau
repository: ThHareau/thhareau.github.io
author: Thomas Hareau
subtitle: Senior Software Engineer @ Doctolib
description: "Thomas Hareau: Senior Software Engineer @ Doctolib"
collections:
  experiences:
    output: false
  achievements:
    output: false
  sections:
    output: false
  blog_posts:
    output: true
    permalink: /blog/:title:output_ext
defaults:
  -
    scope:
      path: ""
    values:
      content_version: "long"
  -
    scope:
      path: "/resume*"
    values:
      content_version: "short"

postcss:
  cache: false