github: [metadata]
encoding: UTF-8
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  syntax_highlighter: rouge
future: true
jailed: false
theme: jekyll-theme-primer
gfm_quirks: paragraph_end

lsi: false
safe: true
incremental: false
gist:
  noscript: false
title: Thomas Hareau
author: Thomas Hareau
subtitle: Senior Software Engineer @ Doctolib
description: "Thomas Hareau: Senior Software Engineer @ Doctolib"
collections:
  - experiences
  - achievements
  - sections
defaults:
  -
    scope:
      path: ""
    values:
      content_version: "long"
  -
    scope:
      path: "/resume*"
    values:
      content_version: "short"